const WIDGET_X_PREFIX = `WIDGET_X`;
const WIDGET_Y_PREFIX = `WIDGET_Y`;

export default {
  X_FIRES_BULLET: `${WIDGET_X_PREFIX}-X_FIRES_BULLET`,
  Y_FIRES_BULLET: `${WIDGET_Y_PREFIX}-Y_FIRES_BULLET`
};
